# Stage 1: Install dependencies
FROM node:21 as deps
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install

# Stage 2: Build the app
FROM node:21 as builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NODE_OPTIONS="--max-old-space-size=4096"
RUN yarn build:staging

# Stage 3: Serve the app
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]